version: '3'

services: 
  baby-pwn:
    build: ./ 
    ports:
      - "3001:1337"
    #cap_add:
    # - SYS_PTRACE
    #security_opt:
    # - apparmor:unconfined
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "10"
          max-size: "1G"
#    volumes:
#      - ./bins:/var/tmp
